jobs:
- job: Linux
  pool:
    vmImage: 'ubuntu-18.04'
  steps:
    - template: ci/linux.yml
- job: Windows
  pool:
    vmImage: 'vs2017-win2016'
  steps:
    - template: ci/windows.yml
- job: Mac
  pool:
    vmImage: 'macOS-10.14'
  steps:
    - template: ci/mac.yml