trigger:
  - master
  - develop

pr:
  branches:
    include:
    - develop

jobs:
- job: UbuntuLinux18GCC7
  pool:
    vmImage: 'ubuntu-18.04'
  steps:
    - template: ci/ubuntu-setup.yml
    - template: ci/linux.yml
      parameters:
        artifactName: ubuntu18_gcc7_release

- job: UbuntuLinux20GCC9
  pool:
    vmImage: 'ubuntu-20.04'
  steps:
    - template: ci/ubuntu-setup.yml
    - template: ci/linux.yml
      parameters:
        artifactName: ubuntu20_gcc9_release

- job: Windows2019
  pool:
    vmImage: 'windows-2019'
  steps:
    - template: ci/windows.yml
      parameters:
        artifactName: win_2019_release

- job: Mac1015
  pool:
    vmImage: 'macOS-10.15'
  steps:
    - template: ci/mac.yml
      parameters:
        artifactName: mac_1015_release

- job: Mac11
  pool:
    vmImage: 'macOS-11'
  steps:
    - template: ci/mac.yml
      parameters:
        artifactName: mac_11_release
