name: Build Hobbits
run-name: Build ${{ github.ref }} ${{ github.sha }}
on:
  push:
    branches:
      - develop
  pull_request:
    branches:
      - develop
jobs:
  Build-Hobbits:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/setup-node@v3
        with:
          node-version: 14
      - name: Check out repo
        uses: actions/checkout@v3
        with:
          submodules: 'true'
      - name: Install Build Tools
        run: sudo apt-get install -y patchelf qtchooser qt5-qmake qtbase5-dev-tools ninja-build cmake g++
      - name: Install Development Libraries
        run: sudo apt-get install -y libusb-1.0-0-dev libpcap-dev qtbase5-dev python3-dev

      - name: Run CMake
        run: cmake -G Ninja -B build -S ${{ github.workspace }}
      - name: Build
        run: cmake --build build

      - name: Run Tests
        run: |
          npm ci
          cd tests
          ./prepare_tests.js
          export QT_DEBUG_PLUGINS=1
          ./test_hobbits.js ${{ github.workspace }}/build/bin/hobbits-runner -p ${{ github.workspace }}/build/plugins
          cd ${{ github.workspace }}
      
      - name: Package Build Artifacts
        run: ninja package -C build
      - uses: actions/upload-artifact@v3
        with:
          name: DEB Packages
          path: build/hobbits-*deb*